### ISSUE TITLE
No HTTPS support

### ISSUE THREAD

**Issue by AlexDaniel** [supernovus/perl6-http-client#11]
It seems like it does not support https. The error I'm getting is pretty straightforward:

```
Unsupported protocol, 'https'.
```

Such a pity!

For those who are wondering if there is any other way, try [HTTP::UserAgent](https://github.com/sergot/http-useragent/) or [LWP::Simple](https://github.com/cosimo/perl6-lwp-simple).

**Comment by supernovus** [comment]
HTTP::Client is just HTTP 1.0 at this point, with some 1.1 support. It has no TLS layer or anything related. Some of the other libraries may be better developed, as I haven't actively worked on this library in a couple years.

**Comment by supernovus** [comment]
Pull request #14 has added basic HTTPS support. Not sure if it's enough to resolve this, but I figured it's worth mentioning in this issue.
